In [97]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [98]:
from dataset import FPDataset
from matcher import HungarianMatcher

import torch

In [99]:
dataset = FPDataset()

100%|██████████| 15594/15594 [00:02<00:00, 7474.89it/s]


In [100]:
batch_size = 5
num_queries = 10
num_classes = len(dataset.label_unique) + 1

batch = [dataset[i][1] for i in range(batch_size)]

predictions = {
    'pred_logits': torch.rand([batch_size, num_queries, num_classes]),
    'pred_boxes': torch.rand([batch_size, num_queries, 2])
}

In [101]:
matcher = HungarianMatcher()

In [103]:
matcher(predictions, batch)

[(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
  tensor([11,  8,  9,  4,  1,  0,  6,  5, 10,  7])),
 (tensor([0, 3, 7, 8, 9]), tensor([0, 1, 2, 4, 3])),
 (tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
  tensor([ 3,  9,  7,  5,  0,  6, 10,  2,  4,  8])),
 (tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
  tensor([ 9, 12, 11,  8, 13,  4,  7,  5,  6, 10])),
 (tensor([0, 1, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 5, 0, 6, 4, 3, 7, 8, 2]))]