In [1]:
%load_ext autoreload
%autoreload 2

In [6]:
from my_dataset_copy import MyDataset
from loss_copy import HungarianLoss

In [3]:
dataset = MyDataset()

100%|██████████| 15594/15594 [00:03<00:00, 4309.81it/s]


In [4]:
last_hidden_size = 50
num_labels = len(dataset.encoder.categories_[0])

In [7]:
import torch

predictions = [
    {
        "class": torch.rand(num_labels + 1),
        "center": torch.rand(1),
        "len": torch.rand(1)
    } for _ in range(last_hidden_size)
]

In [11]:
loss = HungarianLoss(1, 1, last_hidden_size, num_labels)

In [16]:
for _, data in dataset:
    print(loss(predictions, data))

tensor([32.1288])
tensor([24.8012])
tensor([8.4880])
tensor([36.0169])
tensor([15.2279])
tensor([24.2474])
tensor([33.0005])
tensor([29.4438])
tensor([18.9045])
tensor([30.0225])
tensor([28.1009])
tensor([30.4607])
tensor([28.8127])
tensor([30.7551])
tensor([43.2192])
tensor([16.6642])
tensor([12.7801])
tensor([29.1427])
tensor([29.3300])
tensor([37.2130])
tensor([16.9515])
tensor([31.3880])
tensor([44.0447])
tensor([18.4452])
tensor([29.6997])


KeyboardInterrupt: 